version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    image: sparkdataframecomparer_dev
    volumes:
      - ./:/sdc/
      - ./reports:/reports
    container_name: sparkdataframecomparer_dev
    working_dir: /sdc
